const data = [
    {
        "id": "1",
        "restaurant_name": "Sanjusan",
        "location": "Minneapolis-St.Paul",
        "rating": 4,
        "address": "33 N 1st Ave, Minneapolis, MN 55401, USA",
        "restaurant_website": "https://www.sanjusanrestaurant.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=14738210719523656420",
        "price": 3,
        "service_speed": 2,
        "service": 0,
        "wear": 2,
        "vibes": 2,
        "description": "I've dined at Sanjusan on numerous occasions, easily over seven times. It's a fantastic spot to celebrate with friends, offering a unique and enjoyable experience with its delightful fusion of Japanese and Italian cuisine.",
        "photo": "../../src/assets/images/file1.jpg"
    },
    {
        "id": "2",
        "restaurant_name": "Spoon and Stable",
        "location": "Minneapolis-St.Paul",
        "rating": 4,
        "address": "211 N 1st St, Minneapolis, MN 55401, USA",
        "restaurant_website": "http://www.spoonandstable.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=14589547885912538400",
        "price": 4,
        "service_speed": 2,
        "service": 3,
        "wear": 1,
        "vibes": 3,
        "description": "Spoon and Stable offers a truly exceptional quality dining experience. The food and service are consistently excellent, making it ideal for celebrating very special occasions. Though it's on the pricier side, it is worth every penny (be aware of the 21% hospitality charge). Be sure to save room for their amazing desserts!",
        "photo": "../../src/assets/images/file2.jpg"
    },
    {
        "id": "3",
        "restaurant_name": "Bacio",
        "location": "Minneapolis-St.Paul",
        "rating": 4,
        "address": "1571 Plymouth Rd, Minnetonka, MN 55305, USA",
        "restaurant_website": "http://www.baciomn.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=5703972215538570476",
        "price": 3,
        "service_speed": 2,
        "service": 2,
        "wear": 3,
        "vibes": 3,
        "description": "You can always count on Bacio. With consistently excellent food, amazing service, and a cozy atmosphere, it's a truly satisfying experience. My two visits have both been exceptional.",
        "photo": "../../src/assets/images/file3.jpg"
    },
    {
        "id": "4",
        "restaurant_name": "Colossal Cafe",
        "location": "Minneapolis-St.Paul",
        "rating": 3,
        "address": "2315 Como Ave, St Paul, MN 55108, USA",
        "restaurant_website": "http://www.colossalcafe.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=15862338900976925534",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "The Roast Pork Shoulder Bowl at Colossal Cafe is a must-try. The pork is unbelievably tender and flavorful, making it my favorite brunch restaurant.",
        "photo": "../../src/assets/images/file4.jpg"
    },
    {
        "id": "5",
        "restaurant_name": "Porzana",
        "location": "Minneapolis-St.Paul",
        "rating": 2,
        "address": "200 N 1st St, Minneapolis, MN 55401, USA",
        "restaurant_website": "https://www.porzanampls.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=7381161317812956370",
        "price": 1,
        "service_speed": 2,
        "service": 0,
        "wear": 2,
        "vibes": 0,
        "description": "I've generally enjoyed my dining experiences at Porzana, including a memorable birthday celebration. They have a good selection of steaks at various price points. However, the food can sometimes be too salty, and I once had an unpleasant experience with an upset stomach.",
        "photo": "../../src/assets/images/file5.jpg"
    },
    {
        "id": "6",
        "restaurant_name": "Tenka",
        "location": "Minneapolis-St.Paul",
        "rating": 4,
        "address": "1404 W Lake St, Minneapolis, MN 55408, USA",
        "restaurant_website": "http://www.tenkaramen.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=11232081373729385488",
        "price": 2,
        "service_speed": 3,
        "service": 0,
        "wear": 1,
        "vibes": 1,
        "description": "I absolutely adore Tenka! I've been there over 10 times and recommended to more than 15 friends \u2013 even the owner recognizes me and knows my order. I always get the Spicy Tonkotsu Pork Bone Broth. The chashu is so tender, and the broth is refreshing and heavenly. The only thing keeping it from a perfect score was a recent visit when the owner was on a leave, and the ramen wasn't quite up to its usual standard. I can confidently say it would earn a full 5 stars when the owner is present!",
        "photo": "../../src/assets/images/file6.jpg"
    },
    {
        "id": "7",
        "restaurant_name": "Umbra Minneapolis",
        "location": "Minneapolis-St.Paul",
        "rating": 3,
        "address": "708 S 3rd St, Minneapolis, MN 55415, USA",
        "restaurant_website": "http://umbrampls.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=14772919494021567770",
        "price": 3,
        "service_speed": 2,
        "service": 3,
        "wear": 3,
        "vibes": 4,
        "description": "Umbra's atmosphere is truly exquisite. The winter-seasonal gnocchi and duck steak were highlights of the menu, though the flatbread was fairly standard. The ambiance makes it a worthwhile visit.",
        "photo": "../../src/assets/images/file7.jpg"
    },
    {
        "id": "8",
        "restaurant_name": "Ono Hawaiian Plates North Loop",
        "location": "Minneapolis-St.Paul",
        "rating": 2,
        "address": "729 N Washington Ave, Minneapolis, MN 55413, USA",
        "restaurant_website": null,
        "restaurant_gmap": "https://maps.google.com/?cid=10207132579316899327",
        "price": 1,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "For a delicious and surprisingly affordable meal, Ono Hawaiian Plates North Loop is a winner. Their katsu plates, priced around $10, offer generous portions of crispy, flavorful katsu. The food court setting creates a lively atmosphere, ideal for casual get-togethers.",
        "photo": "../../src/assets/images/file8.jpg"
    },
    {
        "id": "9",
        "restaurant_name": "Pizzeria Lola",
        "location": "Minneapolis-St.Paul",
        "rating": 3,
        "address": "5557 Xerxes Ave S, Minneapolis, MN 55410, USA",
        "restaurant_website": "http://www.pizzerialola.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=13606428811552724077",
        "price": 2,
        "service_speed": 2,
        "service": 2,
        "wear": 1,
        "vibes": 1,
        "description": "Pizzeria Lola's Korean-Italian fusion pizzas are a must-try! The Lady Zaza (kimchi pizza) and Korean BBQ pizza are packed with savory flavor and offer a truly unique culinary experience. While their other pizzas are enjoyable, these two are particularly memorable.",
        "photo": "../../src/assets/images/file9.jpg"
    },
    {
        "id": "10",
        "restaurant_name": "Mama's On Washington Square",
        "location": "Bay Area",
        "rating": 5,
        "address": "1701 Stockton St, San Francisco, CA 94133, USA",
        "restaurant_website": "http://www.mamas-sf.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=10254198419123471356",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 1,
        "description": "Mama's on Washington Square holds a special place in my heart as my favorite San Francisco restaurant. Having first discovered it over eight years ago, I've returned multiple times each year. Their Monte Cristo is simply divine - it melts in your mouth. It is a perfect spot for a family meal, especially breakfast or lunch, followed by a stroll through the beautiful nearby parks and streets.",
        "photo": "../../src/assets/images/file10.jpg"
    },
    {
        "id": "11",
        "restaurant_name": "Daeho Kalbiji & Beef Soup",
        "location": "Bay Area",
        "rating": 4,
        "address": "217 W Calaveras Blvd, Milpitas, CA 95035, USA",
        "restaurant_website": "https://www.daeho-kalbijjim.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/zabkpvz85ebsNeQQ7",
        "price": 3,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "Daeho's Braised Short Ribs are truly memorable. The combination of tender short ribs, chewy rice cakes, and savory glass noodles is simply amazing. Although the dish is around $90, it's substantial enough to share comfortably among 3-4 diners.",
        "photo": "../../src/assets/images/file11.jpg"
    },
    {
        "id": "12",
        "restaurant_name": "Baekjeong",
        "location": "Bay Area",
        "rating": 3,
        "address": "2855 Stevens Creek Blvd #1808, Santa Clara, CA 95050, USA",
        "restaurant_website": "https://www.baekjeongkbbq.com/locations-2/",
        "restaurant_gmap": "https://maps.google.com/?cid=3489126062029100240",
        "price": 3,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 2,
        "description": "Baekjeong offers a fantastic setting for a social Korean BBQ experience. Its upscale ambiance makes it ideal for both family outings and get-togethers with friends. Though it's a bit more expensive, the sharable portions and enjoyable atmosphere are well-suited for large groups (from 3-4 people).",
        "photo": "../../src/assets/images/file12.jpg"
    },
    {
        "id": "13",
        "restaurant_name": "Kunjip",
        "location": "Bay Area",
        "rating": 4,
        "address": "1066 Kiely Blvd, Santa Clara, CA 95051, USA",
        "restaurant_website": "https://order.online/store/kunjip-santa-clara-29034336/?hideModal=true&pickup=true&redirected=true",
        "restaurant_gmap": "https://maps.google.com/?cid=5271684668614801742",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 1,
        "description": "For the past 10 years, Kunjip has consistently delivered an authentic Korean dining experience. Their food resembles the flavors of Korea, a quality I deeply appreciate. The kimchi is always delicious, and their Galbi Tang, Sul Lung Tang, and Bibim Naeng Myun are consistently excellent.",
        "photo": "../../src/assets/images/file13.jpg"
    },
    {
        "id": "14",
        "restaurant_name": "Ramen Nagi",
        "location": "Bay Area",
        "rating": 2,
        "address": "2855 Stevens Creek Blvd, Santa Clara, CA 95050, USA",
        "restaurant_website": "http://www.ramennagiusa.com/",
        "restaurant_gmap": "https://maps.google.com/?cid=12016608336662691409",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "I've visited Ramen Nagi twice, and while the flavors haven't been particularly memorable, the ramen is consistently warming and satisfying. It's a solid choice for a comforting bowl of noodles, and I plan on going back!",
        "photo": "../../src/assets/images/file14.jpg"
    },
    {
        "id": "15",
        "restaurant_name": "Vitality Bowl",
        "location": "Bay Area",
        "rating": 3,
        "address": "5110 Cherry Ave #20, San Jose, CA 95118, USA",
        "restaurant_website": "https://vitalitybowls.com/menu/",
        "restaurant_gmap": "https://maps.app.goo.gl/qo1mAjB63n3m8RGaA",
        "price": 1,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "Vitality Bowls is my absolute favorite for acai bowls. They're simply amazing!",
        "photo": "../../src/assets/images/file15.jpg"
    },
    {
        "id": "16",
        "restaurant_name": "Sweet Retreat",
        "location": "Bay Area",
        "rating": 3,
        "address": "846 Blossom Hill Rd d, San Jose, CA 95123",
        "restaurant_website": "http://www.sweet-retreats.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/NivVu6AqWHjkCBMp8",
        "price": 1,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "Sweet Retreat is my absolute favorite frozen yogurt spot. The way they blend real fruit directly into the froyo is incredibly delicious and refreshing. I'm a huge fan of the strawberry-mango and blueberry-banana flavors. While inflation has slightly affected prices, the quality and generous portions still make it worth it.",
        "photo": "../../src/assets/images/file16.jpg"
    },
    {
        "id": "17",
        "restaurant_name": "Paik's Noodle",
        "location": "Bay Area",
        "rating": 2,
        "address": "1520 Kiely Blvd, Santa Clara, CA 95051, USA",
        "restaurant_website": "https://us.orderspoon.com/hong-kong-banjum-paik-s-noodle",
        "restaurant_gmap": "https://maps.app.goo.gl/fc3TDv5zBWLxJLTq5",
        "price": 2,
        "service_speed": 3,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "Paik's Noodle is a great option for delicious and affordable Korean-Chinese food. Their stir-fried jajangmyeon is a standout dish, packed with flavor. While it can get busy during rush hour, the wait is usually short. The overall atmosphere is lively and enjoyable.",
        "photo": "../../src/assets/images/file17.jpg"
    },
    {
        "id": "18",
        "restaurant_name": "Cloud9 Coffee",
        "location": "Bay Area",
        "rating": 2,
        "address": "1901 Embarcadero Rd #103, Palo Alto, CA 94303, USA",
        "restaurant_website": "https://cloud9coffee.net/",
        "restaurant_gmap": "https://maps.app.goo.gl/Q5wbRa2AR7jGp35RA",
        "price": 1,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "Cloud9 Coffee is a charming caf\u00e9 with cute food plating and drinks. Its location away from the city center creates a wonderfully calm and relaxing atmosphere.",
        "photo": "../../src/assets/images/file18.jpg"
    },
    {
        "id": "19",
        "restaurant_name": "Lou Malnati's Pizzeria",
        "location": "Chicago",
        "rating": 1,
        "address": "439 N Wells St, Chicago, IL 60654, USA",
        "restaurant_website": "http://order.loumalnatis.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/F2VzgaU1Sd6qxeCL9",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 1,
        "description": "Lou Malnati's specializes in Chicago deep-dish pizza, offering flexible sizing perfect for groups. While the cheese pull is satisfying, be prepare. Even a single slice can be quite filling.",
        "photo": "../../src/assets/images/file19.jpg"
    },
    {
        "id": "20",
        "restaurant_name": "Cindy's Rooftop",
        "location": "Chicago",
        "rating": 4,
        "address": "12 S Michigan Ave, Chicago, IL 60603, USA",
        "restaurant_website": "http://www.cindysrooftop.com/menus",
        "restaurant_gmap": "https://maps.app.goo.gl/TB7mNYGKAxaQyVJE6",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 2,
        "vibes": 4,
        "description": "Cindy's Rooftop is one of Chicago's most stunning bars. With breathtaking views of Millennium Park (including the Bean) and a beautifully designed interior, the experience is truly delightful.",
        "photo": "../../src/assets/images/file20.jpg"
    },
    {
        "id": "21",
        "restaurant_name": "Ramen San",
        "location": "Chicago",
        "rating": 2,
        "address": "59 W Hubbard St #2, Chicago, IL 60654, USA",
        "restaurant_website": "https://www.ramensan.com/river-north-menus/",
        "restaurant_gmap": "https://maps.app.goo.gl/kjn3u6NiZuEkPex3A",
        "price": 2,
        "service_speed": 3,
        "service": 2,
        "wear": 1,
        "vibes": 1,
        "description": "Compared to some of the more intensely flavored ramen shops, Ramen San offers a gentler, more approachable style. While the broths aren't overly complex, they are nonetheless delicious and provide a comforting foundation for the dish.",
        "photo": "../../src/assets/images/file21.jpg"
    },
    {
        "id": "22",
        "restaurant_name": "Minghin Cuisine",
        "location": "Chicago",
        "rating": 1,
        "address": "215 E Ohio St, Chicago, IL 60611, USA",
        "restaurant_website": "https://www.minghincuisine.com/dimsum-menu?utm_source=google&utm_medium=menu",
        "restaurant_gmap": "https://maps.app.goo.gl/7ttUc4JVCG1xKJeE7",
        "price": 3,
        "service_speed": 2,
        "service": 1,
        "wear": 1,
        "vibes": 0,
        "description": "Despite MingHhn's good reviews and reputation, my experience was mixed. The shrimp shumai was delicious, but the BBQ pork crepe was quite disappointing, and overall, the meal fell short of expectations.",
        "photo": "../../src/assets/images/file22.jpg"
    },
    {
        "id": "23",
        "restaurant_name": "Bavette's Bar & Boeuf",
        "location": "Chicago",
        "rating": 5,
        "address": "218 W Kinzie St, Chicago, IL 60654, USA",
        "restaurant_website": "https://bavettessteakhouse.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/ALnBZGD6a7bjBwpQ6",
        "price": 4,
        "service_speed": 2,
        "service": 4,
        "wear": 3,
        "vibes": 4,
        "description": "Bavette's Bar & Boeuf provided one of my most memorable dining experiences. The exquisite atmosphere, with its beautiful lighting and interior, combined with exceptional service and a truly delicious and tender steak, made for a truly remarkable evening. I highly recommend this steakhouse.",
        "photo": "../../src/assets/images/file23.jpg"
    },
    {
        "id": "24",
        "restaurant_name": "LH Rooftop",
        "location": "Chicago",
        "rating": 4,
        "address": "151 W Adams St, Chicago, IL 60603, USA",
        "restaurant_website": "https://londonhousechicago.com/rooftop",
        "restaurant_gmap": "https://maps.app.goo.gl/xgdeTVFduK2DZEaHA",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 3,
        "vibes": 3,
        "description": "LH Rooftop Bar provides a truly memorable experience, highlighted by its panoramic views of the Chicago Riverwalk. The atmosphere is both refined and vibrant, creating an ideal setting for enjoying expertly crafted cocktails. My chosen drink was delightful, with a refreshing, juicy flavor.",
        "photo": "../../src/assets/images/file24.jpg"
    },
    {
        "id": "25",
        "restaurant_name": "Alpana",
        "location": "Chicago",
        "rating": 2,
        "address": "1000 W Fulton Market, Chicago, IL 60607, USA",
        "restaurant_website": "http://www.alpanachicago.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/HzziwXmNwWerWnsz5",
        "price": 3,
        "service_speed": 2,
        "service": 0,
        "wear": 2,
        "vibes": 3,
        "description": "Alpana's dishes are nicely presented, which adds to the dining experience. However, the steak had a slightly overpowering salty flavor. Though enjoyable, I felt that the quality of the food, considering the price, could have been better.",
        "photo": "../../src/assets/images/file25.jpg"
    },
    {
        "id": "26",
        "restaurant_name": "Tomi Jazz",
        "location": "New York City",
        "rating": 4,
        "address": "225 E 14th St, New York, NY 10003, USA",
        "restaurant_website": "http://www.tomijazz.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/bRfTQvpkSrDoZ6kCA",
        "price": 2,
        "service_speed": 2,
        "service": 3,
        "wear": 2,
        "vibes": 4,
        "description": "Tomi Jazz is a stunning Japanese jazz bar featuring live music and a beautifully intimate, dimly lit interior. The exceptional food and cocktail options enhance the authentic Japanese atmosphere. Be aware that they do not take reservations, and waits of 1-2 hours are common (it's that good)! I recommend arriving around 4:20 pm to minimize your wait to under an hour.",
        "photo": "../../src/assets/images/file26.jpg"
    },
    {
        "id": "27",
        "restaurant_name": "Ess-a-bagel",
        "location": "New York City",
        "rating": 3,
        "address": "831 3rd Ave, New York, NY 10022, USA",
        "restaurant_website": "http://www.ess-a-bagel.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/vqB6jSTVFhNaRKTcA",
        "price": 2,
        "service_speed": 2,
        "service": 1,
        "wear": 1,
        "vibes": 0,
        "description": "Ess-a-Bagel is a well-known destination for bagel lovers, offering a wide range of customizable bagel sandwiches. Even with the typically quick-moving line, they readily accommodated my request to substitute the raw fish in their signature sandwich with bacon. Their generous portions are easily shareable between two people.",
        "photo": "../../src/assets/images/file27.jpg"
    },
    {
        "id": "28",
        "restaurant_name": "Ichiran Ramen NY Times Square",
        "location": "New York City",
        "rating": 5,
        "address": "152 W 49th St, New York, NY 10020, USA",
        "restaurant_website": "https://www.ichiranusa.com/location/times-square/",
        "restaurant_gmap": "https://maps.app.goo.gl/oq7z4gsSfgNQchw16",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "Ichiran Ramen is the best ramen I have ever had in my life. The Times Square location lived up to my high expectations, even exceeding my experience at Ichiran in Tokyo.\u00a0The authentic Japanese interior, complete with individual booths, creates a truly immersive dining experience that complements the outstanding ramen perfectly. This is an absolute must-try for any ramen enthusiast.",
        "photo": "../../src/assets/images/file28.jpg"
    },
    {
        "id": "29",
        "restaurant_name": "UT47 Manhattan",
        "location": "New York City",
        "rating": 4,
        "address": "132 E 47th St, New York, NY 10017, USA",
        "restaurant_website": "https://ut47manhattan.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/AiNYqNWK1WygHu8a6",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 0,
        "description": "UT47 Manhattan is a true hidden gem with spectacular brunch dishes. Their menu offers flavorful, savory options that are perfectly balanced and not overly heavy.",
        "photo": "../../src/assets/images/file29.jpg"
    },
    {
        "id": "30",
        "restaurant_name": "SALSWEE",
        "location": "New York City",
        "rating": 2,
        "address": "180 5th Ave, New York, NY 10010, USA",
        "restaurant_website": null,
        "restaurant_gmap": "https://maps.app.goo.gl/ywJTyV3EtUnwW7ct6",
        "price": 2,
        "service_speed": 2,
        "service": 0,
        "wear": 1,
        "vibes": 2,
        "description": "SALSWEE offers a whimsical selection of desserts, each a work of art with vibrant colors and charming details, making them incredibly picture-worthy.",
        "photo": "../../src/assets/images/file30.jpg"
    },
    {
        "id": "31",
        "restaurant_name": "Soju Haus",
        "location": "New York City",
        "rating": 3,
        "address": "35 W 32nd St, New York, NY 10001, USA",
        "restaurant_website": "http://www.sojuhaus.com/",
        "restaurant_gmap": "https://maps.app.goo.gl/ywJTyV3EtUnwW7ct6",
        "price": 2,
        "service_speed": 3,
        "service": 2,
        "wear": 1,
        "vibes": 1,
        "description": "While some NYC Koreatown restaurants can be underwhelming, Soju Haus stands out as a refreshing exception. Unlike my previous experiences, Soju Haus offers attentive service, a lively atmosphere, and delicious food at reasonable prices. The portions are generous, perfect for sharing with friends, and they even offer complimentary rice bowls and seaweed rice balls before 8 pm!!",
        "photo": "../../src/assets/images/file31.jpg"
    }
]

export default {data}